# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-20.04

container:
  image: debian:bullseye
  options:  "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

steps:
- script: |
    /tmp/docker exec -t -u 0 ci-container \
    sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
  displayName: 'Install Sudo in container'
- script: |
    sudo apt-get update
    sudo apt-get install -y cmake git make build-essential quilt debhelper bc python3 python3-pip sudo libssl-dev libgcc-10-dev
    sudo apt-get install openssl libssl-dev libssl1.1
    mkdir -p $(Pipeline.Workspace)/target
  displayName: 'Install packages'
- checkout: self
  submodules: recursive
- script: |
    cd src/SymCrypt
    sudo pip3 install -r scripts/requirements.txt
    mkdir bin
    cd bin
    cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake-toolchain/LinuxUserMode-AMD64.cmake
    cmake --build .
  displayName: 'Build SymCrypt'
- script: |
    cd src/SymCrypt-OpenSSL
    sudo mkdir -p $HOME
    sudo chown $USER $HOME
    ln -s $(Pipeline.Workspace)/src/SymCrypt ~/SymCrypt
    cp $(Pipeline.Workspace)/SymCrypt/bin/module/AMD64/LinuxUserMode/libsymcrypt.so ./
    cmake .
    make
  displayName: 'Build SymCrypt-OpenSSL'
- script: |
    cp $(Pipeline.Workspace)/*.deb ./
    cp $(Pipeline.Workspace)/SymCrypt/bin/module/AMD64/LinuxUserMode/libsymcrypt.so ./
    cp $(Pipeline.Workspace)/SymCrypt-OpenSSL/SymCryptEngine/dynamic/libsymcryptengine.so ./
  workingDirectory: $(Pipeline.Workspace)/target
  displayName: 'Copy packages'
- publish: $(Pipeline.Workspace)/target
  artifact: fips-symcrypt
  displayName: "Archive packages"
