# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

container: debian:buster

resources:
 repositories:
   - repository: SymCrypt
     type: github
     name: microsoft/SymCrypt
     ref: refs/heads/master
     endpoint: build
   - repository: SymCrypt-OpenSSL
     type: github
     name: microsoft/SymCrypt-OpenSSL
     ref: refs/heads/main
     endpoint: build

steps:
- script: |
    whoami
    groups
    sudo apt-get update
    sudo apt-get install cmake git make build-essential quilt debhelper bc python3 python3-pip sudo libssl-dev libgcc-8-dev -y
    echo 'deb http://deb.debian.org/debian buster-backports main' | sudo tee /etc/apt/sources.list.d/buster-backports.list
    sudo apt-get update
    sudo apt-get -t buster-backports install cmake
  displayName: 'Install packages'
- checkout: SymCrypt
  path: SymCrypt
- checkout: SymCrypt-OpenSSL
  path: SymCrypt-OpenSSL
